apiVersion: v1
kind: Service
metadata:
  namespace: z-test
  labels:
    tier: backend
  name: backend
spec:
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    tier: backend